In [1]:
2-5

-3

In [2]:
(2-5)**2

9

In [3]:
((2-5)**2)**(0.5)

3.0

In [4]:
a = [5,0.75]
b = [2,0.50]

In [5]:
((5-2)**2 + (0.75 - 0.50)**2)**0.5

3.010398644698074

In [6]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

In [7]:
knn = KNeighborsClassifier(n_neighbors=3)

In [8]:
data = pd.read_table('fruit_data_with_colors.txt')

In [9]:
data

    fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    5.8     8.7         0.73
50            4      lemon           unknown   130    6.0     8.2         0.71
51            4      lemon           unknown   116    6.0     7.5         0.72
52            4      lemon           unknown   118    5.9     8.0         0.72
53            4      lemon           unknown   120    6.0     8.4         0.74
54            4      lemon           unknown   116    6.1     8.5         0.71
55            4      lemon           unknown   116    6.3     7.7         0.72
56            4      lemon           unknown   116    5.9     8.1         0.73
57            4      lemon           unknown   152    6.5     8.5         0.72
58            4      lemon           unknown   118    6.1     8.1         0.70

In [10]:
X = data[['mass','height','width','color_score']]
y = data['fruit_label']

In [11]:
X

    mass  height  width  color_score
0    192     7.3    8.4         0.55
1    180     6.8    8.0         0.59
2    176     7.2    7.4         0.60
3     86     4.7    6.2         0.80
4     84     4.6    6.0         0.79
5     80     4.3    5.8         0.77
6     80     4.3    5.9         0.81
7     76     4.0    5.8         0.81
8    178     7.8    7.1         0.92
9    172     7.0    7.4         0.89
10   166     7.3    6.9         0.93
11   172     7.6    7.1         0.92
12   154     7.1    7.0         0.88
13   164     7.7    7.3         0.70
14   152     7.3    7.6         0.69
15   156     7.1    7.7         0.69
16   156     7.5    7.6         0.67
17   168     7.6    7.5         0.73
18   162     7.1    7.5         0.83
19   162     7.2    7.4         0.85
20   160     7.5    7.5         0.86
21   156     7.4    7.4         0.84
22   140     7.1    7.3         0.87
23   170     7.9    7.6         0.88
24   342     9.4    9.0         0.75
25   356     9.2    9.2         0.75
26   362     9.2    9.6         0.74
27   204     9.2    7.5         0.77
28   140     7.1    6.7         0.72
29   160     7.4    7.0         0.81
30   158     7.5    7.1         0.79
31   210     8.0    7.8         0.82
32   164     7.0    7.2         0.80
33   190     8.1    7.5         0.74
34   142     7.8    7.6         0.75
35   150     7.9    7.1         0.75
36   160     7.6    7.1         0.76
37   154     7.3    7.3         0.79
38   158     7.8    7.2         0.77
39   144     7.4    6.8         0.75
40   154     7.5    7.1         0.78
41   180     8.2    7.6         0.79
42   154     7.2    7.2         0.82
43   194    10.3    7.2         0.70
44   200    10.5    7.3         0.72
45   186     9.2    7.2         0.72
46   216    10.2    7.3         0.71
47   196     9.7    7.3         0.72
48   174    10.1    7.3         0.72
49   132     8.7    5.8         0.73
50   130     8.2    6.0         0.71
51   116     7.5    6.0         0.72
52   118     8.0    5.9         0.72
53   120     8.4    6.0         0.74
54   116     8.5    6.1         0.71
55   116     7.7    6.3         0.72
56   116     8.1    5.9         0.73
57   152     8.5    6.5         0.72
58   118     8.1    6.1         0.70

In [12]:
y

0     1
1     1
2     1
3     2
4     2
5     2
6     2
7     2
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    4
44    4
45    4
46    4
47    4
48    4
49    4
50    4
51    4
52    4
53    4
54    4
55    4
56    4
57    4
58    4
Name: fruit_label, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [15]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [16]:
knn.score(X_test,y_test)

0.6

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
mm = MinMaxScaler()

In [19]:
X_train = mm.fit_transform(X_train)

In [20]:
X_train

array([[0.27972028, 0.53846154, 0.47368421, 0.31578947],
       [0.02797203, 0.09230769, 0.05263158, 0.63157895],
       [0.33566434, 0.55384615, 0.34210526, 0.97368421],
       [0.22377622, 0.47692308, 0.23684211, 0.44736842],
       [0.14685315, 0.61538462, 0.02631579, 0.44736842],
       [0.27272727, 0.49230769, 0.36842105, 0.71052632],
       [0.34265734, 0.93846154, 0.39473684, 0.44736842],
       [0.43356643, 1.        , 0.39473684, 0.44736842],
       [0.32867133, 0.6       , 0.47368421, 0.86842105],
       [0.40559441, 0.50769231, 0.68421053, 0.        ],
       [0.93006993, 0.83076923, 0.84210526, 0.52631579],
       [0.3006993 , 0.49230769, 0.42105263, 0.78947368],
       [0.31468531, 0.50769231, 0.28947368, 1.        ],
       [1.        , 0.8       , 1.        , 0.5       ],
       [0.27972028, 0.52307692, 0.42105263, 0.76315789],
       [0.38461538, 0.8       , 0.36842105, 0.44736842],
       [0.28671329, 0.53846154, 0.34210526, 0.63157895],
       [0.30769231, 0.56923077, 0.39473684, 0.39473684],
       [0.30769231, 0.46153846, 0.36842105, 0.65789474],
       [0.01398601, 0.04615385, 0.        , 0.57894737],
       [0.33566434, 0.46153846, 0.42105263, 0.89473684],
       [0.27972028, 0.47692308, 0.5       , 0.36842105],
       [0.        , 0.        , 0.        , 0.68421053],
       [0.41258741, 0.96923077, 0.36842105, 0.39473684],
       [0.29370629, 0.53846154, 0.44736842, 0.81578947],
       [0.26573427, 0.69230769, 0.18421053, 0.44736842],
       [0.36363636, 0.43076923, 0.57894737, 0.10526316],
       [0.03496503, 0.10769231, 0.10526316, 0.65789474],
       [0.13986014, 0.56923077, 0.13157895, 0.44736842],
       [0.23776224, 0.52307692, 0.26315789, 0.52631579],
       [0.27272727, 0.53846154, 0.34210526, 0.60526316],
       [0.13986014, 0.69230769, 0.07894737, 0.42105263],
       [0.18881119, 0.64615385, 0.05263158, 0.42105263],
       [0.27272727, 0.47692308, 0.31578947, 0.86842105],
       [0.25874126, 0.6       , 0.34210526, 0.52631579],
       [0.44755245, 0.8       , 0.44736842, 0.57894737],
       [0.23076923, 0.58461538, 0.47368421, 0.52631579],
       [0.22377622, 0.47692308, 0.39473684, 0.84210526],
       [0.01398601, 0.04615385, 0.02631579, 0.68421053],
       [0.13986014, 0.63076923, 0.02631579, 0.47368421],
       [0.15384615, 0.67692308, 0.05263158, 0.5       ],
       [0.36363636, 0.64615385, 0.47368421, 0.63157895],
       [0.35664336, 0.58461538, 0.34210526, 0.97368421],
       [0.26573427, 0.50769231, 0.47368421, 0.36842105]])

In [21]:
X_test = mm.transform(X_test)

In [22]:
X_test

array([[0.29370629, 0.52307692, 0.31578947, 0.68421053],
       [0.32167832, 0.55384615, 0.44736842, 0.47368421],
       [0.13986014, 0.53846154, 0.05263158, 0.44736842],
       [0.14685315, 0.63076923, 0.07894737, 0.39473684],
       [0.29370629, 0.55384615, 0.34210526, 0.55263158],
       [0.48951049, 0.95384615, 0.39473684, 0.42105263],
       [0.3986014 , 0.63076923, 0.44736842, 0.5       ],
       [0.34965035, 0.49230769, 0.42105263, 0.13157895],
       [0.1958042 , 0.72307692, 0.        , 0.47368421],
       [0.28671329, 0.58461538, 0.36842105, 0.57894737],
       [0.27272727, 0.50769231, 0.39473684, 0.63157895],
       [0.97902098, 0.8       , 0.89473684, 0.52631579],
       [0.41958042, 0.87692308, 0.39473684, 0.44736842],
       [0.3006993 , 0.47692308, 0.44736842, 0.73684211],
       [0.46853147, 0.61538462, 0.52631579, 0.71052632]])

In [23]:
knn = KNeighborsClassifier(n_neighbors=3)

In [24]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [25]:
knn.score(X_test,y_test)

0.9333333333333333

In [26]:
knn.predict(X_test)

array([3, 1, 4, 4, 3, 4, 3, 1, 4, 3, 3, 3, 4, 1, 1])

In [27]:
y_test

29    3
17    1
51    4
58    4
36    3
46    4
33    3
2     1
49    4
38    3
37    3
25    3
47    4
18    1
31    3
Name: fruit_label, dtype: int64

In [28]:
from sklearn.neighbors import KNeighborsRegressor

In [29]:
knn = KNeighborsRegressor(n_neighbors=3)

Nesta etapa, utilizaremos o conjunto de dados California Housing, disponibilizado pelo Scikit-learn, como alternativa ao antigo conjunto Boston Housing, que foi removido das versões atuais da biblioteca. O objetivo é aplicar o algoritmo KNeighborsRegressor para realizar uma tarefa de regressão, utilizando dados de treinamento e teste para avaliar o desempenho do modelo.

In [30]:
from sklearn.datasets import fetch_california_housing

In [31]:
data = fetch_california_housing()

In [32]:
X, y = data.data, data.target

In [33]:
X.shape

(20640, 8)

In [34]:
y.shape

(20640,)

In [35]:
print(data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib:
https://lib.stat.cmu.edu/datasets/houses.zip

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [38]:
knn.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [39]:
knn.score(X_test, y_test)

0.13229200262442642

In [40]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [41]:
knn = KNeighborsRegressor(n_neighbors=3)

In [42]:
data = fetch_california_housing()

In [43]:
X, y = data.data, data.target

In [44]:
X.shape

(20640, 8)

In [45]:
y.shape

(20640,)

In [46]:
print(data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib:
https://lib.stat.cmu.edu/datasets/houses.zip

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [48]:
mm = MinMaxScaler()

In [49]:
X_train = mm.fit_transform(X_train)

In [50]:
X_test = mm.transform(X_test)

In [51]:
knn.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [52]:
knn.score(X_test, y_test)

0.6938838132432177

In [53]:
knn.predict(X_test)

array([3.351     , 2.75633333, 1.87366667, ..., 2.346     , 2.21      ,
       3.56200333], shape=(5160,))

In [54]:
y_test

array([3.527, 2.432, 1.798, ..., 1.971, 0.807, 3.227], shape=(5160,))